### PR TITLE
Add minimal man pages

### PR DESCRIPTION
**Pull request by He-Ro**
This adds minimal man pages for llpp, llppac, and llpphtml.
This only really makes sense, if these man pages will be kept up to date, but I think it would be quite benificial.
Please also check that the description of the options is correct. And also elaborate on some of the short option descriptions, as I was no shure what they were doing exactly.

### CODE REVIEW

**Comment by moosotc** [comment]
He-Ro <notifications@github.com> writes:

> This adds minimal man pages for llpp, llppac, and llpphtml.
> This only really makes sense, if these man pages will be kept up to date, but I think it would be quite benificial.
> Please also check that the description of the options is correct. And also elaborate on some of the short option descriptions, as I was no shure what they were doing exactly.
> You can view, comment on, or merge this pull request online at:
>

Thank you! Will review thoroughly later, quick first glance notes.

[..snip..]

It is based on the MuPDF library and uses default keybindings that
resemble less(1).

Technically this is incorrect, given existence of:
http://repo.or.cz/llpp.git/shortlog/refs/heads/dejavu
[Granted nobody, myself included, uses that, was more or less a proof of
concept, but still...]

More apt wording would probably be:
"Normally MuPDF[link} is used to render various documents"

-cxack [undocumented]

-embed X11-window-id
[Given that llpp runs under macOS]

-last
It opens last _visited_ document. Not last document (whatever that is)
:)

AUTHOR
moosotc@gmail.com et al.

Once again, thank you.

--
mailto:moosotc@gmail.com

**Comment by He-Ro** [comment]
Good point. The wording in general can be discussed, changed and improved upon. This is just a minimal setup to create (hopefully) maintainable man pages.

**Comment by moosotc** [comment]
He-Ro <notifications@github.com> writes:

> Good point. The wording in general can be discussed, changed and
> improved upon. This is just a minimal setup to create (hopefully)
> maintainable man pages.

Author field irks me... et al. does not give Nicolás enough credit :(

-- 
mailto:moosotc@gmail.com

**Comment by He-Ro** [comment]
> Author field irks me... et al. does not give Nicolás enough credit :(

I can totally understand that. I suggest you look over the pages and change them to your liking. This should be considered a starting point of the man pages, not the final form ;)

To build them you need `xmlto` and `asciidoc`. And then you can view them with e.g. `make; man -l llpp.1`

**Comment by moosotc** [comment]
He-Ro <notifications@github.com> writes:

>> Author field irks me... et al. does not give Nicolás enough credit :(
>
> I can totally understand that. I suggest you look over the pages and
> change them to your liking. This should be considered a starting point
> of the man pages, not the final form ;)

That's problematic:

~
- xmlto
zsh: command not found: xmlto

~
- pkgfile xmlto
extra/xmlto
~
- sudo pacman -S xmlto
resolving dependencies...
looking for conflicting packages...

Packages (1) xmlto-0.0.28-2

Total Download Size:   0.02 MiB
Total Installed Size:  0.07 MiB

Not as bad as I imagined it would be.

>
> To build them you need `xmlto` and `asciidoc`. And then you can view
> them with e.g. `make; man -l llpp.1`

asciidoc was installed here... I will try to build the pages a bit later
today.

-- 
mailto:moosotc@gmail.com

**Comment by eli-schwartz** [comment]
xmlto is not necessary either.

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/llpp#n21
https://git.archlinux.org/svntogit/community.git/tree/trunk/Makefile?h=packages/llpp#n63

**Pull request merged**
