### PR TITLE
build.sh: respect $CFLAGS

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by tuncer** [comment]
Something similar should be done in Shake.hs.

**Comment by tuncer** [comment]
Something similar should be done in Build.hs.

**Comment by moosotc** [comment]
Tuncer Ayaz <notifications@github.com> writes:

> Something similar should be done in Shake.hs.
>

No idea how to do this though, Shake might (or might not) have an
ability to get command line arguments. And if one goes for environment
variables then there is:

~% ghci
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Prelude> System.Environment.getEnv "moo"
*** Exception: moo: getEnv: does not exist (no environment variable)

and I have no clue how to handle exceptions in Haskell.

-- 
mailto:moosotc@gmail.com

**Comment by tuncer** [comment]
In `Development.Shake` there's `getEnv :: String -> Action (Maybe String)` and `getEnvWithDefault :: String -> String -> Action String`. There's also a config module ([Development.Shake.Config](https://hackage.haskell.org/package/shake/docs/Development-Shake-Config.html)), but it doesn't seem to consider env vars.

**Comment by tuncer** [comment]
Have you merged this already, and can this ticket be closed?

**Comment by moosotc** [comment]
Tuncer Ayaz <notifications@github.com> writes:

> Have you merged this already, and can this ticket be closed?

Aye.

-- 
mailto:moosotc@gmail.com

**Comment by tuncer** [comment]
Merged, closing.

**Comment by moosotc** [comment]
Tuncer Ayaz <notifications@github.com> writes:

> In `Development.Shake` there's `getEnv :: String -> Action (Maybe
> String)` and `getEnvWithDefault :: String -> String -> Action
> String`. There's also a config module
> ([Development.Shake.Config](https://hackage.haskell.org/package/shake/docs/Development-Shake-Config.html)),
> but it doesn't seem to consider env vars.
>

Thanks, getEnvWithDefault sounds like what's needed, but alas, trying to
make use of it just showed how impure and unmonadic I am. IOW I've
failed...

-- 
mailto:moosotc@gmail.com

**Comment by ndmitchell** [comment]
For info, the way to do this in Shake is getEnvWithDefault, and it should be as simple as:

    flags2 <- words <$> getEnvWithDefault "" "CFLAGS"

If you want to explain where the failure arose, I should be able to point out the issue. As an added bonus, changing your CFLAGS environment variable will rebuild the right pieces.

**Comment by moosotc** [comment]
Neil Mitchell <notifications@github.com> writes:

> For info, the way to do this in Shake is getEnvWithDefault, and it
> should be as simple as:
>
>     flags2 <- words <$> getEnvWithDefault "" "CFLAGS"
>
> If you want to explain where the failure arose, I should be able to
> point out the issue. As an added bonus, changing your CFLAGS
> environment variable will rebuild the right pieces.
>

Thanks, but... plugging this line into the current code yields:

Shakefile.hs:162:23:
    Couldn't match type `Action' with `IO'
    Expected type: IO String
      Actual type: Action String
    In the second argument of `(<$>)', namely
      `getEnvWithDefault "" "CFLAGS"'
    In a stmt of a 'do' block:
      flags2 <- words <$> getEnvWithDefault "" "CFLAGS"

-- 
mailto:moosotc@gmail.com

**Comment by ndmitchell** [comment]
So there are two places you can put it. Either you can put it on line 162, before calling shakeArgs, in which case it won't be tracked, but will still work much the same as a Makefile CFLAGS variable. If so, you want to use [`System.Environment.lookupEnv`](https://hackage.haskell.org/package/base-4.8.1.0/docs/System-Environment.html#v:lookupEnv). Alternatively, you can use `getEnvWithDefault` inside a rule where you actually use the cflags variable, e.g. line 198. You will end up calling `getEnvWithDefault` multiple times, but it's quick, and then if you change the CFLAGS variable the right things will rebuild. Your choice which you prefer in your project.

**Comment by moosotc** [comment]
Neil Mitchell <notifications@github.com> writes:

> So there are two places you can put it. Either you can put it on line
> 162, before calling shakeArgs, in which case it won't be tracked, but
> will still work much the same as a Makefile CFLAGS variable. If so,
> you want to use
> [`System.Environment.lookupEnv`](https://hackage.haskell.org/package/base-4.8.1.0/docs/System-Environment.html#v:lookupEnv). Alternatively,
> you can use `getEnvWithDefault` inside a rule where you actually use
> the cflags variable, e.g. line 198. You will end up calling
> `getEnvWithDefault` multiple times, but it's quick, and then if you
> change the CFLAGS variable the right things will rebuild. Your choice
> which you prefer in your project.

The former works, thank you. And oracles take care of tracking.

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by ndmitchell** [comment]
Great! Yes, I hadn't realised the oracles, so tracked environment variables are superfluous.

**Pull request closed without merging**
