### PR TITLE
Implement missing tunables -S & -s

### PR DESCRIPTION
**Pull request by softmoth**
These were documented in help but never implemented. Note that intentry
does error checking so (int_of_string s) should always succeed.

Negative values are allowed for both parameters (as when set via info
mode), and may actually be useful for both. Negative scroll step does
inverse scrolling, and negative inter-page space makes pages overlap in
a reasonable way.

### CODE REVIEW

**Comment by moosotc** [comment]
Tim Smith <notifications@github.com> writes:

> <#multipart type=alternative>
> <#part type=text/plain charset="UTF-8" disposition=inline nofile=yes>
> These were documented in help but never implemented. Note that intentry
> does error checking so (int_of_string s) should always succeed.
>

Thanks for the patch, that said - they were implemented, but then
removed by: beb31b9179972f03b4a22347a6119471cdc37a45

It's just that help screen wasn't properly patched it seems.

Unless you really need those, i'd rather help.ml be fixed.

> Negative values are allowed for both parameters (as when set via info
> mode), and may actually be useful for both. Negative scroll step does
> inverse scrolling, and negative inter-page space makes pages overlap in
> a reasonable way.
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/moosotc/llpp/pull/109
>
> -- Commit Summary --
>
>   * Implement missing tunables -S & -s
>
> -- File Changes --
>
>     M main.ml (34)
>
> -- Patch Links --
>
> https://github.com/moosotc/llpp/pull/109.patch
> https://github.com/moosotc/llpp/pull/109.diff
> rt>

-- 
mailto:moosotc@gmail.com

**Comment by softmoth** [comment]
I've updated this PR to just remove the help text. Thanks!

**Comment by moosotc** [comment]
Tim Smith <notifications@github.com> writes:

> I've updated this PR to just remove the help text. Thanks!

I'm not sure how to apply that and preserve attribution.. Can you,
please, prepare a separate/self-contained patch that just removes stuff
from help.ml? Thanks.

-- 
mailto:moosotc@gmail.com

**Comment by softmoth** [comment]
It should allow you to commit it with the button on https://github.com/moosotc/llpp/pull/109, I believe. But if this works better:

```
From 9228bf7a6d7db40e46851509cd7db2c25505e01f Mon Sep 17 00:00:00 2001
From: Tim Smith <tim.dolores@gmail.com>
Date: Fri, 15 Feb 2019 11:43:46 -0700
Subject: [PATCH 1/1] Remove unwanted tunables from help text

---
 help.ml | 2 --
 1 file changed, 2 deletions(-)

diff --git a/help.ml b/help.ml
index 30d8bdf..1f5c60b 100644
--- a/help.ml
+++ b/help.ml
@@ -100,8 +100,6 @@ S                   - slide show mode

 -----Tunables-----
 -i          - toggle case sensitivity of searches
--s<number>  - set scroll step (pixels)
--S<number>  - set space between pages (pixels)
 -R<number>  - rotate
 -v          - toggle verbosity
 -Z<number>  - set zoom (percent)
--
2.20.1

```

**Comment by moosotc** [comment]
Tim Smith <notifications@github.com> writes:

Applied, thanks!

-- 
mailto:moosotc@gmail.com

**Pull request closed without merging**
