### PR TITLE
Fix two 4.04.0 warnings that broke (Werr) the build

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by moosotc** [comment]
Tuncer Ayaz <notifications@github.com> writes:

> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/moosotc/llpp/pull/36

Heh, I already fixed those locally, haven't pushed because of the other
changes to main.ml, thanks! Will probably use your version to not fuck
local things up.

>
> -- Commit Summary --
>
>   * Fix two 4.04.0 warnings that broke (Werr) the build
>
> -- File Changes --
>
>     M config.ml (2)
>     M main.ml (2)
>
> -- Patch Links --
>
> https://github.com/moosotc/llpp/pull/36.patch
> https://github.com/moosotc/llpp/pull/36.diff

-- 
mailto:moosotc@gmail.com

**Comment by tuncer** [comment]
Have you also adapted to upstream `FZ_LINK*` changes?

**Comment by moosotc** [comment]
Tuncer Ayaz <notifications@github.com> writes:

> Have you also adapted to upstream `FZ_LINK*` changes?

Not yet, there's mupdf's work in progress to be pushed once the release
is made, and some local changes (not yet comprehensive) and with a
special branch (Tor's link-coord).

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Tuncer Ayaz <notifications@github.com> writes:

> Have you also adapted to upstream `FZ_LINK*` changes?

Pushed WIP stuff (only internal links assuredly work)

 4 files changed, 52 insertions(+), 146 deletions(-)

Me likee...

-- 
mailto:moosotc@gmail.com

**Pull request merged**
